version: "3"

services:
  py:
    build: .
    volumes:
      - './app:/app'
  db-service:
    image: mariadb:5.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_data
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
